### ISSUE TITLE
Learning Programing Language

### ISSUE THREAD

**Issue by febridev** [boringPpl/data-engineer-roadmap#2]
I see your data engineer roadmap
i see part of learn programming language (java, scala, python). this is what i need to learn ?? i mean all programming language like java, scala and python. or i need learn one ??

**Comment by san089** [comment]
I mean not all. The most widely used language in Data Science and especially in Data Engineering is Python. Also, it would be much easier to learn python than Scala or Java if you do not have a computer science or software engineering background. So I would say learning python would be a great starting point. 

Then you can start looking into Scala and Java which are also used in Data Engineering. I have come across various Data Engineering Projects using Scala to build ETL Pipelines. I have not seen much Java in Data Engineering but it has been used in Data Streaming projects involving Apache Kafka. 

It would be very overwhelming for you to learn all 3 languages. I would suggest starting with Python as it is comparatively easier to learn, then once you have the grip of Data Engineering maybe you can look into other languages as you move from one project to other.

**Comment by iamkaiwei** [comment]
I will say start by picking 1. 

I will recommend Scala or java if you are actually developing tools or flows. If you are doing data cleaning, start with python.
